### ISSUE TITLE
TODO: Rendering

### ISSUE THREAD

**Issue by SinTh0r4s** [SinTh0r4s/HydroEnergy#12]
HETesselator:
- [x] Instread of freeing GPU buffers -> reassign them to another chunk
- [x] Create sorted list for all vao at rendering and call all backsides and frontsides batched to save state changes

HEProgram:
- [x] Add animated textures
- [x] Add brightness to waterId
- [x] Rename waterId to waterBitfield or something
- [x] Compact worldColorModifier to use less bit -> 24bits are enough
- [x] Use waterLevel from global state
- [x] Get transparency right
- [x] Integrate vanilla fog to rendering (currently it is drawn over)

DebugMode:
- [x] If dam is set to debug mode: render max water level && change texture/color tint

Last:
- [x] Remove old render code
- [x] Reimplement lighting hack
- [x] Post in LWJGL Forum to solve render setup format missmatch
- [x] Adapt technique to HE.max_controllers: We want multiple dams!
