### ISSUE TITLE
TODO: Blocks

### ISSUE THREAD

**Issue by SinTh0r4s** [SinTh0r4s/HydroEnergy#15]
HEDams:
- [x] Create list of required saved data
- [x] Save and load global instance data
- [x] Limit spreading
- [x] Modify spreading to also remove water
- [x] Force render debug if controller is not placed
- [x] Verify valid separation between client and server
- [x] Make demo video
